[2024-06-12T07:53:13.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T07:53:13.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.preprocessing_data_task manual__2024-06-12T07:53:11.702738+00:00 [queued]>
[2024-06-12T07:53:13.542+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.preprocessing_data_task manual__2024-06-12T07:53:11.702738+00:00 [queued]>
[2024-06-12T07:53:13.544+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-12T07:53:13.678+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocessing_data_task> on 2024-06-12 07:53:11.702738+00:00
[2024-06-12T07:53:13.686+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2908) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T07:53:13.687+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'preprocessing_data_task', 'manual__2024-06-12T07:53:11.702738+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpzhasaspm']
[2024-06-12T07:53:13.688+0000] {standard_task_runner.py:63} INFO - Started process 2943 to run task
[2024-06-12T07:53:13.688+0000] {standard_task_runner.py:91} INFO - Job 100: Subtask preprocessing_data_task
[2024-06-12T07:53:13.727+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.preprocessing_data_task manual__2024-06-12T07:53:11.702738+00:00 [running]> on host ad0cd89ef011
[2024-06-12T07:53:13.792+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='preprocessing_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T07:53:11.702738+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T07:53:11.702738+00:00'
[2024-06-12T07:53:13.793+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T07:53:13.797+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T07:53:13.798+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 72, in preprocessing_data
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-06-12T07:53:13.809+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=preprocessing_data_task, run_id=manual__2024-06-12T07:53:11.702738+00:00, execution_date=20240612T075311, start_date=20240612T075313, end_date=20240612T075313
[2024-06-12T07:53:13.822+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 100 for task preprocessing_data_task (No module named 'matplotlib'; 2943)
[2024-06-12T07:53:13.862+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T07:53:13.874+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T07:53:13.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
