[2024-06-11T16:10:05.870+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T16:10:05.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.collect_data manual__2024-06-11T16:09:58.379489+00:00 [queued]>
[2024-06-11T16:10:05.920+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.collect_data manual__2024-06-11T16:09:58.379489+00:00 [queued]>
[2024-06-11T16:10:05.920+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-11T16:10:05.934+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2024-06-11 16:09:58.379489+00:00
[2024-06-11T16:10:05.958+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=157) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T16:10:05.958+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'collect_data', 'manual__2024-06-11T16:09:58.379489+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpmpyg5swf']
[2024-06-11T16:10:05.964+0000] {standard_task_runner.py:63} INFO - Started process 201 to run task
[2024-06-11T16:10:05.965+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask collect_data
[2024-06-11T16:10:06.099+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.collect_data manual__2024-06-11T16:09:58.379489+00:00 [running]> on host 9f57110a8ef6
[2024-06-11T16:10:06.237+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T16:09:58.379489+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T16:09:58.379489+00:00'
[2024-06-11T16:10:06.239+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T16:10:07.180+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T16:10:07.181+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 33, in collect_data
    data.to_csv('/opt/airflow/data/stock_data.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/data'
[2024-06-11T16:10:07.238+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=collect_data, run_id=manual__2024-06-11T16:09:58.379489+00:00, execution_date=20240611T160958, start_date=20240611T161005, end_date=20240611T161007
[2024-06-11T16:10:07.263+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task collect_data (Cannot save file into a non-existent directory: '/opt/***/data'; 201)
[2024-06-11T16:10:07.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T16:10:07.332+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T16:10:07.334+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
