[2024-06-13T16:05:52.125+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T16:05:52.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.send_email_task manual__2024-06-13T16:04:24.261969+00:00 [queued]>
[2024-06-13T16:05:52.157+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.send_email_task manual__2024-06-13T16:04:24.261969+00:00 [queued]>
[2024-06-13T16:05:52.158+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T16:05:52.168+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_email_task> on 2024-06-13 16:04:24.261969+00:00
[2024-06-13T16:05:52.177+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=27776) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T16:05:52.179+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'send_email_task', 'manual__2024-06-13T16:04:24.261969+00:00', '--job-id', '534', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpgg08_q1u']
[2024-06-13T16:05:52.179+0000] {standard_task_runner.py:63} INFO - Started process 27801 to run task
[2024-06-13T16:05:52.180+0000] {standard_task_runner.py:91} INFO - Job 534: Subtask send_email_task
[2024-06-13T16:05:52.216+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.send_email_task manual__2024-06-13T16:04:24.261969+00:00 [running]> on host 33b4ab31339c
[2024-06-13T16:05:52.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T16:04:24.261969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T16:04:24.261969+00:00'
[2024-06-13T16:05:52.283+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T16:05:52.298+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T16:05:52.299+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 340, in send_email
    send_email_with_html_and_csv_attachments(sender_email, receiver_email,
  File "/opt/airflow/dags/send_email.py", line 21, in send_email_with_html_and_csv_attachments
    with open(image_path, 'rb') as attachment:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/visualize/visualize_train.csv'
[2024-06-13T16:05:52.318+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=send_email_task, run_id=manual__2024-06-13T16:04:24.261969+00:00, execution_date=20240613T160424, start_date=20240613T160552, end_date=20240613T160552
[2024-06-13T16:05:52.329+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 534 for task send_email_task ([Errno 2] No such file or directory: '/opt/airflow/data/visualize/visualize_train.csv'; 27801)
[2024-06-13T16:05:52.355+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T16:05:52.373+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T16:05:52.374+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
