[2024-06-12T07:28:11.234+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T07:28:11.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.describe_data_task manual__2024-06-12T07:28:02.595482+00:00 [queued]>
[2024-06-12T07:28:11.253+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.describe_data_task manual__2024-06-12T07:28:02.595482+00:00 [queued]>
[2024-06-12T07:28:11.254+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-12T07:28:11.275+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): describe_data_task> on 2024-06-12 07:28:02.595482+00:00
[2024-06-12T07:28:11.287+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2447) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T07:28:11.289+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'describe_data_task', 'manual__2024-06-12T07:28:02.595482+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpzk63hnib']
[2024-06-12T07:28:11.293+0000] {standard_task_runner.py:63} INFO - Started process 2465 to run task
[2024-06-12T07:28:11.293+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask describe_data_task
[2024-06-12T07:28:11.330+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.describe_data_task manual__2024-06-12T07:28:02.595482+00:00 [running]> on host ad0cd89ef011
[2024-06-12T07:28:11.385+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='describe_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T07:28:02.595482+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T07:28:02.595482+00:00'
[2024-06-12T07:28:11.386+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T07:28:11.409+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T07:28:11.410+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 54, in describe_data
    df["time"] = pd.to_datetime(df.time, format="%Y/%m/%d")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 488, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 519, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 534, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 355, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "2014-01-02" doesn't match format "%Y/%m/%d", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[2024-06-12T07:28:11.424+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=describe_data_task, run_id=manual__2024-06-12T07:28:02.595482+00:00, execution_date=20240612T072802, start_date=20240612T072811, end_date=20240612T072811
[2024-06-12T07:28:11.440+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 93 for task describe_data_task (time data "2014-01-02" doesn't match format "%Y/%m/%d", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.; 2465)
[2024-06-12T07:28:11.467+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T07:28:11.490+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T07:28:11.494+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
