[2024-06-13T02:22:38.248+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T02:22:38.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:17:55.578872+00:00 [queued]>
[2024-06-13T02:22:38.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:17:55.578872+00:00 [queued]>
[2024-06-13T02:22:38.342+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T02:22:38.378+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-13 02:17:55.578872+00:00
[2024-06-13T02:22:38.402+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2285) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T02:22:38.408+0000] {standard_task_runner.py:63} INFO - Started process 2310 to run task
[2024-06-13T02:22:38.406+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'manual__2024-06-13T02:17:55.578872+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpy161xl6f']
[2024-06-13T02:22:38.410+0000] {standard_task_runner.py:91} INFO - Job 305: Subtask test_model_task
[2024-06-13T02:22:38.512+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:17:55.578872+00:00 [running]> on host 33b4ab31339c
[2024-06-13T02:22:38.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T02:17:55.578872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T02:17:55.578872+00:00'
[2024-06-13T02:22:38.707+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T02:22:41.268+0000] {logging_mixin.py:188} INFO -  1/82 ━━━━━━━━━━━━━━━━━━━━ 1:25 1s/step
[2024-06-13T02:22:41.320+0000] {logging_mixin.py:188} INFO -  5/82 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step
[2024-06-13T02:22:41.377+0000] {logging_mixin.py:188} INFO - 10/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:22:41.432+0000] {logging_mixin.py:188} INFO - 15/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:22:41.490+0000] {logging_mixin.py:188} INFO - 21/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:22:41.542+0000] {logging_mixin.py:188} INFO - 26/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:22:41.594+0000] {logging_mixin.py:188} INFO - 31/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:22:41.645+0000] {logging_mixin.py:188} INFO - 36/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:22:41.703+0000] {logging_mixin.py:188} INFO - 42/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:22:41.761+0000] {logging_mixin.py:188} INFO - 48/82 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[2024-06-13T02:22:41.811+0000] {logging_mixin.py:188} INFO - 53/82 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[2024-06-13T02:22:41.870+0000] {logging_mixin.py:188} INFO - 59/82 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[2024-06-13T02:22:41.921+0000] {logging_mixin.py:188} INFO - 64/82 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[2024-06-13T02:22:41.980+0000] {logging_mixin.py:188} INFO - 70/82 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[2024-06-13T02:22:42.040+0000] {logging_mixin.py:188} INFO - 76/82 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[2024-06-13T02:22:42.093+0000] {logging_mixin.py:188} INFO - 80/82 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[2024-06-13T02:22:42.916+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[2024-06-13T02:22:42.918+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step
[2024-06-13T02:22:43.091+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T02:22:43.093+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 276, in test_model
    x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
                                                  ~~~~~~~~~~~~^^^
IndexError: tuple index out of range
[2024-06-13T02:22:43.143+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=test_model_task, run_id=manual__2024-06-13T02:17:55.578872+00:00, execution_date=20240613T021755, start_date=20240613T022238, end_date=20240613T022243
[2024-06-13T02:22:43.180+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 305 for task test_model_task (tuple index out of range; 2310)
[2024-06-13T02:22:43.236+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T02:22:43.256+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
