[2024-06-11T17:00:16.709+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T17:00:16.724+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.update_data manual__2024-06-11T17:00:10.672836+00:00 [queued]>
[2024-06-11T17:00:16.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.update_data manual__2024-06-11T17:00:10.672836+00:00 [queued]>
[2024-06-11T17:00:16.730+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-11T17:00:16.741+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): update_data> on 2024-06-11 17:00:10.672836+00:00
[2024-06-11T17:00:16.748+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T17:00:16.750+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'update_data', 'manual__2024-06-11T17:00:10.672836+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmp4or6u3uc']
[2024-06-11T17:00:16.750+0000] {standard_task_runner.py:63} INFO - Started process 1126 to run task
[2024-06-11T17:00:16.751+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask update_data
[2024-06-11T17:00:16.780+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.update_data manual__2024-06-11T17:00:10.672836+00:00 [running]> on host ad0cd89ef011
[2024-06-11T17:00:16.834+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='update_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T17:00:10.672836+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T17:00:10.672836+00:00'
[2024-06-11T17:00:16.836+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T17:00:17.185+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T17:00:17.186+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 50, in update_data
    new_data = new_data[new_data['time'] > start_date]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 56, in __gt__
    return self._cmp_method(other, operator.gt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5803, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 346, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 131, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'datetime.date' and 'str'
[2024-06-11T17:00:17.204+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=update_data, run_id=manual__2024-06-11T17:00:10.672836+00:00, execution_date=20240611T170010, start_date=20240611T170016, end_date=20240611T170017
[2024-06-11T17:00:17.222+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task update_data ('>' not supported between instances of 'datetime.date' and 'str'; 1126)
[2024-06-11T17:00:17.247+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T17:00:17.280+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T17:00:17.283+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
