[2024-06-13T15:09:08.833+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T15:09:08.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.send_email_task manual__2024-06-13T15:07:48.446991+00:00 [queued]>
[2024-06-13T15:09:08.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.send_email_task manual__2024-06-13T15:07:48.446991+00:00 [queued]>
[2024-06-13T15:09:08.858+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T15:09:08.868+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_email_task> on 2024-06-13 15:07:48.446991+00:00
[2024-06-13T15:09:08.878+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=24911) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T15:09:08.880+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'send_email_task', 'manual__2024-06-13T15:07:48.446991+00:00', '--job-id', '515', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmp5bz14ed_']
[2024-06-13T15:09:08.880+0000] {standard_task_runner.py:63} INFO - Started process 24929 to run task
[2024-06-13T15:09:08.881+0000] {standard_task_runner.py:91} INFO - Job 515: Subtask send_email_task
[2024-06-13T15:09:08.927+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.send_email_task manual__2024-06-13T15:07:48.446991+00:00 [running]> on host 33b4ab31339c
[2024-06-13T15:09:08.991+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T15:07:48.446991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T15:07:48.446991+00:00'
[2024-06-13T15:09:08.992+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T15:09:11.299+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T15:09:11.302+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/send_email.py", line 38, in send_email_with_html_and_csv_attachment
    session.login(from_email, password)
  File "/usr/local/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired 98e67ed59e1d1-2c4aa59ff02sm3989914a91.1 - gsmtp')
[2024-06-13T15:09:11.313+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=send_email_task, run_id=manual__2024-06-13T15:07:48.446991+00:00, execution_date=20240613T150748, start_date=20240613T150908, end_date=20240613T150911
[2024-06-13T15:09:11.323+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 515 for task send_email_task ((534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired 98e67ed59e1d1-2c4aa59ff02sm3989914a91.1 - gsmtp'); 24929)
[2024-06-13T15:09:11.351+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T15:09:11.365+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T15:09:11.368+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
